### ISSUE TITLE
[feature] Add playback device selector

### ISSUE THREAD

**Issue by Guisch** [micahmo/SoundBoard#11]
Hey 🖖 

Thanks for the tool, it's quite cool and fun to use :)
I would like to propose you to add a way to select the playback device so you can route audio to a specific speaker.
I know that you can do it directly in Windows but it's quite buggy and I have the feeling that the app sometime force route the audio to the default playback device.

Here is an example of how Discord is doing it
![img](https://i.redd.it/votkk6jjyx701.png)

Thanks :)

**Comment by micahmo** [comment]
Hi @Guisch,

Thanks for the idea! I just published an update ([v1.7](https://github.com/micahmo/SoundBoard/releases/tag/v1.7)) with this feature. I have a pretty limited setup to test (in terms of audio devices), so if anything does not work with your setup, feel free to open additional issues.

P.S. You will have to download 1.7 manually, but the app now has built-in update functionality, so you should not have to download any future updates manually.

**Comment by Guisch** [comment]
Hey 🖖 
Tested it yersteday and it works like a charm. Thanks for adding this feature so quickly, truely appreciate
