### ISSUE TITLE
Windows Defender

### ISSUE THREAD

**Issue by Guisch** [micahmo/SoundBoard#12]
Hey, since today (April 13th), your software is being tagged as a Trojan by Windows Defender (Trojan:Win32/Zpevdo.B). I launched an analysis on Virustotal and Hybridanalysis so you can take a look why. I believe it's have to do with the [online version checking](https://raw.githubusercontent.com:443/micahmo/SoundBoard/master/SoundBoard/VersionInfo.xml
) for update I guess.

https://www.hybrid-analysis.com/sample/da0b5bdc053706bae495f21cfb9ad8ccaae682e42f70c0e7a2875443014618e4
https://www.virustotal.com/gui/file/da0b5bdc053706bae495f21cfb9ad8ccaae682e42f70c0e7a2875443014618e4/behavior/C2AE

**Comment by micahmo** [comment]
Hi @Guisch, thanks for the head's up! Interestingly enough, I use the same auto update mechanism in several projects, and the others seem to be fine (for now!). I'll look into this. Thanks again.

**Comment by micahmo** [comment]
Still not 100% sure what's going on, but it looks like building a new binary gets around the flag for now.

Feel free to grab [v1.7.1](https://github.com/micahmo/SoundBoard/releases/tag/v1.7.1) and let me know if it works for you.

I've also seen it suggested that one can [submit files to Microsoft](https://www.microsoft.com/en-us/wdsi/filesubmission) for validation that it is not malware, and it may help with the annoying SmartScreen warning too!

**Comment by micahmo** [comment]
Update! Microsoft reviewed and removed the incorrect identification!

Here are their comments:
```
Analyst comments:

We have removed the detection. Please follow the steps below to clear cached detection and obtain the latest malware definitions.

1. Open command prompt as administrator and change directory to c:\Program Files\Windows Defender
2. Run “MpCmdRun.exe -removedefinitions -dynamicsignatures”
3. Run "MpCmdRun.exe -SignatureUpdate"

Alternatively, the latest definition is available for download here: https://www.microsoft.com/en-us/wdsi/definitions
```

Sure enough, I ran the commands that they suggested, and I'm now able to download and run [v1.7](https://github.com/micahmo/SoundBoard/releases/tag/v1.7) successfully again.

@Guisch, if that works for you too, I'll close this issue.

**Comment by Guisch** [comment]
All good. thank you for your responsiveness !
