### ISSUE TITLE
Multiple audio outputs

### ISSUE THREAD

**Issue by ThEditor** [micahmo/SoundBoard#14]
The ability to add multiple audio outputs. 

My current setup pipes my microphone to a virtual audio cable and the soundboard pipes audio to the same. 
This way, the audio gets piped through my microphone but the problem is I can't heard the audio myself.

I am currently using the "listen to" feature from windows to listen to the audio but that way I have listen to my own voice too.
The ability to support multiple audio outputs will solve this issue.

**Comment by micahmo** [comment]
Hey @ThEditor, thanks for the suggestion! I will have to see if this is something Windows and [NAudio](https://github.com/naudio/NAudio) support.

In the meantime, I wonder if there's any other way to accomplish what you want. Depending on the target of your audio you may be able to use another virtual audio device.

For example, I use OBS. It can detect desktop audio, but that's every sound your desktop makes, which I don't want. I made a virtual audio device with [Voicemeeter](https://vb-audio.com/Voicemeeter/index.htm), piped SoundBoard to that, and used that as my audio input in OBS. Then I used OBS's monitor feature to pipe that audio input back out so I could hear it over the desktop. And of course, the mic input is totally separate in OBS, so if you don't monitor it, you don't have to hear yourself.

I don't know if you're using anything like OBS, but maybe something along those lines would help until I can dig into this.

**Comment by micahmo** [comment]
Hey @ThEditor, I have an update on this. I did find that routing a media file to multiple devices is not really something that's supported by Windows or NAudio.

However, I also found that it's possible to simply open multiple streams of the same file, one for each audio device, and play them in parallel. This seems to work pretty well and I think it should cover your use case.

![image](https://user-images.githubusercontent.com/7417301/144777028-c5703857-d576-4475-bac1-54299e29d648.png)
> Access multi-selection by right-clicking on the device(s). Left-click selects a single device.

**The major caveat is that these streams cannot really be synchronized, so it is possible for them to drift. The drift should be relatively small, though, and would only really be a factor if you were ultimately piping both audio outputs back to a single one where you could hear both streams.**

Would you be willing to try the beta version I've just posted with this feature and let me know if it's stable for you? Note that you can run it on the same machine that has your existing version, although I'd highly recommended backing up the current version via the "Export configuration" menu item if you can't afford to lose your data.

https://github.com/micahmo/SoundBoard/releases/tag/v1.8-beta1

Thanks!

**Comment by ThEditor** [comment]
I've tested it out and it seems to work perfectly. For my use case, I don't necessarily need it to be in complete synchronization so that's fine too.
Thanks!

**Comment by micahmo** [comment]
Awesome, I'm glad to hear that! I will leave it in beta for a little while, and if there are no issues, I'll promote to a release. Thanks for trying it out!

**Comment by micahmo** [comment]
Closed by [v1.8](https://github.com/micahmo/SoundBoard/releases/tag/v1.8)
