### ISSUE TITLE
Invisible Titles After Import

### ISSUE THREAD

**Issue by EddyLuten** [micahmo/SoundBoard#17]
After importing an existing configuration from another system, all sounds show up without visible titles. Everything else copies over fine, including background colors, sounds, etc.

When I create a new page, the titles are visible on it, but there's no way for me to make the imported ones visible again. I've tried renaming them, but they remain invisible.

System Info:

SoundBoard 1.9.0.2
Windows 11 21H2 (Build 22000.593)
Surface Pro 6

Steps to reproduce:

- Export a configuration file on system A
- Import the configuration file on system B
- Observe that the sound titles are invisible

**Comment by EddyLuten** [comment]
After messing with the device for a bit, the titles show up in portrait mode and when I turn off UI scaling (set to 200% by default for this device). This issue seems to be related to either resolution or scale.

The grids of my pages are set to 10x3, and the display resolution is 2736x1824 @ 200% scaling.

I will turn off UI scaling as a workaround while using this application for the time being.

**Comment by micahmo** [comment]
Hey @EddyLuten, sorry about this issue and thanks for the report! I'll admit that I've never tested this app at 200% scaling, and there's some funky logic that's supposed to handle resizing the titles so that they shrink/wrap nicely as the window size and title length changes. I will see if there's anything I can do to make this work better at 200%

**Comment by micahmo** [comment]
Hey @EddyLuten, I'm not sure if you still use SoundBoard, but I have made some improvements to text resizing in the [latest release](https://github.com/micahmo/SoundBoard/releases/tag/v1.10.0). I wasn't able to test it on a system with your resolution/scaling, so if there are still issues, feel free to send a screenshot and I'll see if I can help!

**Comment by EddyLuten** [comment]
@micahmo, sorry, I didn't see the follow-ups on this conversation. I no longer use the app since I'm using a hardware solution now for my soundboard, but thank you for the diligence 👍
