### ISSUE TITLE
Feature Request: Play Next / Playlist / Hold Macros

### ISSUE THREAD

**Issue by MadDog443** [micahmo/SoundBoard#21]
It would be really handy to be able to create a playlist of sounds that I could sort into order and then it would play the clip on the first activation of the macro and then wait till I hit it again to play the next so that I could cycle through a set of clips in cases of limited key space and for improved timing with skits. It would also be great to be able to have the initial macro and continue/cycle macro be separate.

**Comment by micahmo** [comment]
Hey @MadDog443, thanks for the suggestion, I like this idea. It will take some work to make it intuitive and user-friendly.

Regarding the "playlist" setup, is the current "next sound" feature sufficient for chaining things together? Then the only ask would be to delay activation of the next sound until a given hotkey is pressed.

**Comment by MadDog443** [comment]
Actually that was my thought exactly. The current tab design is already so similar that adding a wait function macro would fulfill this idea.

**Comment by micahmo** [comment]
> The current tab design

Just to make sure we're on the same page, I was referring to the "Next sound" option that lets one sound queue another (and thus allows chaining).

![image](https://user-images.githubusercontent.com/7417301/233488193-4dd696ff-8c90-4a24-9cd2-2b11b3fd5821.png)

There would be an additional option for delayed activation. Does that work?

Also for the hotkey, should it be global or per sequence? The latter would be trickier since you could start anywhere in the sequence.

Thanks for the feedback!

**Comment by MadDog443** [comment]
Absolutely. I was thinking global, kinda like a resume button, otherwise it'd be no different than just making another macro.

**Comment by micahmo** [comment]
Hey @MadDog443, thanks again for the suggestion and feedback. Would you have some time to test out a release candidate containing this feature?

Here's how it works:
 - As discussed, you can use the "Next sound" menu option to chain sounds together and create your sequence.
 - You can also select the new "Pause next sound activation" option.

![image](https://user-images.githubusercontent.com/7417301/234107765-96450705-266f-4df4-b2f0-81fc7414ebcf.png)

When a sound with "next" and "pause" finishes, you will see this snackbar appear at the bottom. You can manually continue or cancel the sequence. You can also configure a local and/or global hotkey to activate the next sound. (Local/global here refers to app- or system-level hotkeys. They both apply to all sound sequences.)

![image](https://user-images.githubusercontent.com/7417301/234108045-91dd811f-865c-4c66-a5e4-937d95cafdf4.png)

You can configure the hotkeys from the top-level menu.

![image](https://user-images.githubusercontent.com/7417301/234108169-16f0f9bd-4505-4ccb-80c7-bbd2e8973e34.png)

A couple other notes:
 - You can cancel the sequence with Escape.
 - You have to set "Pause next sound activation" on each sound in the sequence. But you can use multiselect to speed this up.
 - Only one sequence can be in progress at a time.

You should be able to run this side-by-side with your current version, but I always recommend exporting your current config before testing, in case anything gets corrupted.

[SoundBoard.zip](https://github.com/micahmo/SoundBoard/files/11314422/SoundBoard.zip)

Thanks!

**Comment by micahmo** [comment]
Hey @MadDog443, did you ever get a chance to test out this feature?
