### ISSUE TITLE
Won't Run

### ISSUE THREAD

**Issue by 737simpilot** [micahmo/SoundBoard#22]
Double click the .exe and nothing. Using Windows 10.

**Comment by micahmo** [comment]
Hey @737simpilot, thanks for the report! I just booted a clean Windows 10 and was able to reproduce. A few minutes later I tried again and it happened to work! Maybe Windows Defender was scanning it or something. Can you try again?

**Comment by 737simpilot** [comment]
My Windows Defender is off. Also, your EXE shows up on radar at VirusTotal.

**Comment by micahmo** [comment]
I'm not sure if Smart Screen runs even when Windows Defender is off. I run all my applications through Microsoft's self-submission scanning to try to prevent things like that (can't really do anything about third-party tools).

Did you try launching it again some time after the initial download? Do you have any other antivirus?

Let me submit the app to Microsoft again just in case.

**Comment by EKSIFYT** [comment]
i had the same problem try running it as administrator
